name: Validate PR
on:
  pull_request:

env:
  ReportOutput: '${{github.workspace}}'
  TestReportFileName: 'TestReport.${{github.run_number}}.md'
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

  # Dotnet Setup
  DOTNET_VERSION: 3.1.401

  # Stop wasting time caching packages
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

  # Disable sending usage data to Microsoft
  DOTNET_CLI_TELEMETRY_OPTOUT: true

  # Solution Setup
  CONFIG: 'Release'

  # Nuget Setup
  NUGET_VERSION: 'latest'

jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    env:
      # Stop wasting time caching packages
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

      # Disable sending usage data to Microsoft
      DOTNET_CLI_TELEMETRY_OPTOUT: true

      # Solution Setup
      CONFIG: 'Release'
      PROJECT_NAME: ${{ github.event.repository.name }}
      VERSION: '1.0.0'

      # Release Setup
      NUGET_VERSION: 'latest'
      NUGET_OUTPUT: '.nuget_output'
      BINARIES_OUTPUT: '.binaries_output'

    steps:
      - name: Checkout reference commit
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/checkout@v2

      - name: Checkout master
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: 0

      - name: Get version
        if: ${{ github.event_name != 'pull_request' }}
        shell: bash
        run: |
          tag_check=$(git describe --exact-match `git rev-parse HEAD` | head -1)
          echo "VERSION=$tag_check" >> $GITHUB_ENV

      - uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'

      - name: Setup .NET 5.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Setup .NET 6.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Configure NuGet
        uses: nuget/setup-nuget@v1
        with:
          nuget-version: ${{ env.NUGET_VERSION }}

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build
        run: |
          dotnet build \
            -c ${{ env.CONFIG }} \
            --no-restore

      - name: Set PR build number
        id: PRNUMBER
        if: ${{ github.event_name == 'pull_request' }}
        uses: kkak10/pr-number-action@v1.3

      - name: Set Test Title
        run: |
          echo "::set-env name=title::Test Run for PR #${{ steps.PRNUMBER.outputs.pr }} (${{ github.run_number }})"

      - name: Run Tests
        run: dotnet test --no-restore --no-build --configuration ${{ env.CONFIG }} --logger:"liquid.md;LogFileName=${{ env.ReportOutput}}\${{ env.TestReportFileName }};Title=${{ env.Title }};"

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: results
          path: ${{ env.ReportOutput}}\${{ env.TestReportFileName }}

  commenting:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v2

      - uses: actions/download-artifact@v1
        with:
          name: results

      - name: Comment PR
        uses: machine-learning-apps/pr-comment@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: results/${{ env.TestReportFileName }}